In [1]:
import pandas as pp
import matplotlib.pyplot as mm
%matplotlib inline 
import numpy as nn
import seaborn as ss

In [18]:
a = pp.read_csv("Food demand.csv")
a

id  week  center_id  meal_id  checkout_price  base_price  \
0     1000000     3        157     2760          233.83      231.83   
1     1000001   100        104     2956          486.03      583.03   
2     1000002   143         75     1971          328.86      327.86   
3     1000003    41         24     2539          145.53      145.53   
4     1000004    45         83     2539           95.06      120.34   
...       ...   ...        ...      ...             ...         ...   
1994  1002177    89         72     1311          130.04      177.51   
1995  1002178    24         50     2444          604.31      606.31   
1996  1002179    43         88     1971          291.06      291.06   
1997  1002180   107         58     1543          473.39      473.39   
1998  1002181   105        177     2322          284.27      284.27   

      emailer_for_promotion  homepage_featured  num_orders  
0                         0                  0         149  
1                         0                  0         161  
2                         0                  0         149  
3                         0                  0         540  
4                         0                  0         271  
...                     ...                ...         ...  
1994                      0                  0          68  
1995                      0                  0         109  
1996                      0                  0         366  
1997                      0                  1          42  
1998                      0                  0         485  

[1999 rows x 9 columns]

In [41]:
a['emailer_for_promotion'].unique()

array([0, 1])

In [42]:
a['homepage_featured'].unique()

array([0, 1])

In [44]:
a['homepage_featured'].value_counts()

homepage_featured
0    1789
1     210
Name: count, dtype: int64

In [19]:
a.shape

(1999, 9)

In [20]:
a.isnull().sum() # no null values in the given dataset

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
dtype: int64

In [21]:
from sklearn import linear_model# importing the linear model from the sklearn 

In [53]:
r = linear_model.LinearRegression()
r.fit(a[['id','week','center_id' ,'meal_id','checkout_price','base_price','emailer_for_promotion','homepage_featured']],a.num_orders)

LinearRegression()

In [54]:
r.coef_


array([ 1.18661236e-02, -2.84201511e-01, -1.67741042e-01,  2.01562455e-03,
       -6.64890872e-01,  4.57271554e-02,  3.09764612e+02,  2.31740330e+02])

In [55]:
r.intercept_

-11436.028106605181

In [56]:
a['week'].unique()

array([  3, 100, 143,  41,  45, 101, 107,  11, 114,  68,  10,  18,  33,
       140, 105, 112, 131,   9,  88, 111,  49,   6,  30,  91, 104,  83,
        95,  24,  97,  25,  90,   4, 109, 139,  85, 141,  40, 120,  86,
        64,  42,  31,  93,   1, 133, 144,  51,   5,  98, 135,   7,  94,
        78, 118,  26,  73, 113,   8,  32, 122,  21,  28, 130,  92, 132,
        56, 124,  65, 134, 110,  59,  35, 119,  55, 127,  67,  19,  69,
       106,  36,  82,  75,  47, 102,  37, 115,  84, 116,  22,  12,  96,
        48,  70,  80,  54,  15, 129,  14,  44,  63, 103, 136, 121,  87,
        57,  46,  76,  77,  20,  38, 108,  34,  60, 142, 125,  17, 138,
        74, 137, 126,  13,  66,  58,  62,   2,  53,  81,  50,  16, 145,
        52, 117,  27,  89,  99,  61, 128,  39,  23,  71,  72,  43,  79,
       123,  29])

In [57]:
a['center_id'].unique()

array([157, 104,  75,  24,  83,  65, 153,  50,  57,  36,  76,  88,  81,
        43,  77,  80,  92,  52,  89,  68,  55,  14,  41,  97,  94, 174,
       145,  10, 186,  93,  58, 137,  34, 101,  11,  29, 124, 143, 129,
        73, 126,  59,  66,  26,  13,  53, 109,  39,  99, 110,  30, 106,
        23, 146,  51,  72,  17,  32,  67,  64,  91,  74, 149, 139, 161,
       162, 132, 177, 108,  61,  42,  20, 113,  86, 102,  27, 152])

In [50]:
a['meal_id'].unique()

array([2760, 2956, 1971, 2539, 1754, 2126, 1062, 1962, 1216, 2867, 2494,
       1571, 2139, 2290, 2826, 1445, 1311, 2704, 1248, 1109, 2640, 1885,
       1207, 2490, 2581, 1558, 1878, 1543, 2664, 2631, 2492, 2577, 2569,
       1727, 1778, 1525, 1770, 1247, 2306, 2707, 2304, 2322, 2444, 1198,
       1803, 1993, 1902, 1230, 1847, 2104, 1438])

In [58]:
a['id'].unique()

array([1000000, 1000001, 1000002, ..., 1002179, 1002180, 1002181])

In [64]:
r.predict([[1002181,105,177,2322,284.27,284.27,0,1]])

/Users/devanshgupta/anaconda3/lib/python3.11/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([456.85512047])